<a href="https://colab.research.google.com/github/WISEPLAT/_NN/blob/main/nn_training_2_layer_network.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import sys

In [2]:
class PartyNN(object):
    
    def __init__(self, learning_rate=0.1):
        self.weights_0_1 = np.random.normal(0.0, 2 ** -0.5, (2, 3))
        self.weights_1_2 = np.random.normal(0.0, 1, (1, 2))
        print(self.weights_0_1)
        print(self.weights_1_2)
        self.sigmoid_mapper = np.vectorize(self.sigmoid)
        self.learning_rate = np.array([learning_rate])
        
    def sigmoid(self, x):
        return 1 / (1 + np.exp(-x))
    
    def predict(self, inputs):
        inputs_1 = np.dot(self.weights_0_1, inputs)
        outputs_1 = self.sigmoid_mapper(inputs_1)
        
        inputs_2 = np.dot(self.weights_1_2, outputs_1)
        outputs_2 = self.sigmoid_mapper(inputs_2)
        return outputs_2
    
    def train(self, inputs, expected_predict):     
        inputs_1 = np.dot(self.weights_0_1, inputs)
        outputs_1 = self.sigmoid_mapper(inputs_1)
        
        inputs_2 = np.dot(self.weights_1_2, outputs_1)
        outputs_2 = self.sigmoid_mapper(inputs_2)
        actual_predict = outputs_2[0]
        
        error_layer_2 = np.array([actual_predict - expected_predict])
        gradient_layer_2 = actual_predict * (1 - actual_predict)
        weights_delta_layer_2 = error_layer_2 * gradient_layer_2  
        self.weights_1_2 -= (np.dot(weights_delta_layer_2, outputs_1.reshape(1, len(outputs_1)))) * self.learning_rate
        
        error_layer_1 = weights_delta_layer_2 * self.weights_1_2
        gradient_layer_1 = outputs_1 * (1 - outputs_1)
        weights_delta_layer_1 = error_layer_1 * gradient_layer_1
        self.weights_0_1 -= np.dot(inputs.reshape(len(inputs), 1), weights_delta_layer_1).T  * self.learning_rate

In [3]:
def MSE(y, Y):
    return np.mean((y-Y)**2)

In [4]:
train = [
    ([0, 0, 0], 0),
    ([0, 0, 1], 1),
    ([0, 1, 0], 0),
    ([0, 1, 1], 0),
    ([1, 0, 0], 1),
    ([1, 0, 1], 1),
    ([1, 1, 0], 0),
    ([1, 1, 1], 0),
]

In [5]:
#epochs = 5000
#learning_rate = 0.05
epochs = 6000
learning_rate = 0.08

network = PartyNN(learning_rate=learning_rate)

for e in range(epochs):
    inputs_ = []
    correct_predictions = []
    for input_stat, correct_predict in train:
        network.train(np.array(input_stat), correct_predict)
        inputs_.append(np.array(input_stat))
        correct_predictions.append(np.array(correct_predict))
    
    train_loss = MSE(network.predict(np.array(inputs_).T), np.array(correct_predictions))
    sys.stdout.write("\rProgress: {}, Training loss: {}".format(str(100 * e/float(epochs))[:4], str(train_loss)[:5]))

[[-0.25495527 -0.9641784   1.30276498]
 [-0.31955163 -0.44172229  0.68482623]]
[[ 0.3794752  -0.17542757]]
Progress: 99.9, Training loss: 0.002

In [6]:
for input_stat, correct_predict in train:
    print("For input: {} the prediction is: {}, expected: {}".format(
        str(input_stat), 
        str(network.predict(np.array(input_stat)) > .5),
        str(correct_predict == 1)))

For input: [0, 0, 0] the prediction is: [False], expected: False
For input: [0, 0, 1] the prediction is: [ True], expected: True
For input: [0, 1, 0] the prediction is: [False], expected: False
For input: [0, 1, 1] the prediction is: [False], expected: False
For input: [1, 0, 0] the prediction is: [ True], expected: True
For input: [1, 0, 1] the prediction is: [ True], expected: True
For input: [1, 1, 0] the prediction is: [False], expected: False
For input: [1, 1, 1] the prediction is: [False], expected: False


In [7]:
for input_stat, correct_predict in train:
    print("For input: {} the prediction is: {}, expected: {}".format(
        str(input_stat), 
        str(network.predict(np.array(input_stat))),
        str(correct_predict == 1)))

For input: [0, 0, 0] the prediction is: [0.09420503], expected: False
For input: [0, 0, 1] the prediction is: [0.94518638], expected: True
For input: [0, 1, 0] the prediction is: [0.00017748], expected: False
For input: [0, 1, 1] the prediction is: [0.00041226], expected: False
For input: [1, 0, 0] the prediction is: [0.94454587], expected: True
For input: [1, 0, 1] the prediction is: [0.98284743], expected: True
For input: [1, 1, 0] the prediction is: [0.00040841], expected: False
For input: [1, 1, 1] the prediction is: [0.02752628], expected: False


In [8]:
network.weights_0_1

array([[ 1.90219883, -4.39326299,  2.08258232],
       [-2.2317233 ,  4.78218045, -2.14557492]])

In [9]:
network.weights_1_2

array([[ 4.2342772 , -8.76095605]])